version: '3'
services:
  snapserver:
    container_name: snapserver
    command: snapserver -c /config/snapserver.conf
    image: ssalaues/snapcast
    volumes:
      - /tmp:/tmp
      - /data/docker/snapserver/config:/config
    restart: always
    network_mode: host
    user: "0"
